return {
	class = require('class'),
	enums = require('enums'),
	package = require('./package.lua'),
	Client = require('client/Client'),
	Clock = require('utils/Clock'),
	Color = require('utils/Color'),
	Cache = require('utils/Cache'),
	Date = require('utils/Date'),
	Deque = require('utils/Deque'),
	Emitter = require('utils/Emitter'),
	Mutex = require('utils/Mutex'),
	Stopwatch = require('utils/Stopwatch'),
	Permissions = require('utils/Permissions'),
	Time = require('utils/Time'),
}
